### ISSUE TITLE
docker not found error when trying to run ci command with docker

### ISSUE THREAD

**Issue by aminify** [vegardit/docker-gitea-act-runner#2]
Hi there
I'm very new to ci/cd and setting up services. But I managed to run gitea alongside this runner successfully. In my actions I want to do a `docker build` after `checkout` but I get the error that `docker is not found`. I think this is really silly. Should I somehow manually install docker in the runner?

**Comment by sebthom** [comment]
good catch, yes the docker client was missing. I added it to the docker image, please give it a try.

**Comment by joaolongo** [comment]
I'm also having this issue, I tried the updated container, but still getting the error. Should I clean the volume and start the runner fresh?

**Comment by sebthom** [comment]
I missed to add the binary to the final image. should work now. thanks for the feedback.

**Comment by joaolongo** [comment]
Thank you! I don´t know if it is related, but the newer version is not finding node in PATH.

**Comment by sebthom** [comment]
I don't think that is related. Node should not be required in the container that executes the act_runner. act_runner basically just spawns other docker containers (that may need node).

**Comment by joaolongo** [comment]
True, On the docker side, still no luck. It is giving the docker not found error.

**Comment by joaolongo** [comment]
The problem is, the node16 container that the runner spawns has no docker CLI, even though the volumemap to the docker.sock is there.

**Comment by sebthom** [comment]
ok, so the act-runner container doesn't need the docker client after all.

**Comment by sebthom** [comment]
> The problem is, the node16 container that the runner spawns has no docker CLI, even though the volumemap to the docker.sock is there.

the volume map alone is not suffient. the container also needs to have the docker client binary if it tries to invoke the docker command

**Comment by joaolongo** [comment]
> ok, so the act-runner container doesn't need the docker client after all.

I'm not sure, because the runner needs to spawn the children containers.



> > The problem is, the node16 container that the runner spawns has no docker CLI, even though the volumemap to the docker.sock is there.
> 
> the volume map alone is not sufficient. the container also needs to have the docker client binary if it tries to invoke the docker command

Exactly, the problem is that right now the act runner only spawns node:16 children, I don't know if this is an upstream bug frlm gitea, or if I'm doing something wrong on my configurations.

**Comment by joaolongo** [comment]
> Apparently this was an issue from the runner image and that didn't have docker installed. I managed to fix this issue using `ubuntu-latest:docker://catthehacker/ubuntu:act-22.04` as`GITEA_RUNNER_LABELS` env variable when running the docker container.

This is it! @sebthom, if not specified, maybe the docker image should use these labels as default:

- ubuntu-20.04:docker://node:16-bullseye
- ubuntu-18.04:docker://node:16-buster
- ubuntu-latest:docker://catthehacker/ubuntu:act-22.04

Otherwise the runners will be created only using node:16, and with no docker support.

There are other image examples that can by found on [here](https://github.com/catthehacker/docker_images).

Thanks for your help @aminify!

PS.: I'm still not sure if the docker client is needed or not, if you need someone to help you test it, ping me @sebthom

**Comment by sebthom** [comment]
@joaolongo that sounds like a good idea. I am a.f.k. at the moment but will get back to this next week.

**Comment by sebthom** [comment]
I reverted the inclusion of the docker client in the runner docker image as it has no effect and changed the default labels to use `catthehacker/ubuntu:runner-**` docker images.

**Comment by sebthom** [comment]
Closing the issue for now. Feel free to reopen if required.
